### ISSUE TITLE
Update ember models to match new schema

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/ember-mapbox-composer#7] opened 2018-09-07 20:43 UTC

**Comment by allthesignals** [comment] 2018-09-11 16:46
Having trouble reproducing this issue in mapbox composer. I think this may be specific to streets.

**Comment by allthesignals** [comment] 2018-09-11 16:48
This has to do with `labs-ui`, which is very strict about the arguments it receives:
<img width="701" alt="screen shot 2018-09-11 at 12 47 34 pm" src="https://user-images.githubusercontent.com/5004319/45374696-dfed0180-b5c0-11e8-8aef-f4cb78347220.png">

**Comment by allthesignals** [comment] 2018-09-11 16:49
@chriswhong @andycochran I'll need more information because this is a bit of a fishing expedition.

**Comment by allthesignals** [comment] 2018-09-11 17:14
Having trouble fixing this at all because of the setup for SCSS: https://github.com/NYCPlanning/labs-ui/issues/10.

**Comment by chriswhong** [comment] 2018-10-10 20:11
https://github.com/NYCPlanning/labs-citymap/blob/develop/app/models/layer-group.js

We just encountered this again on waterfront access app, had to copy the above model from streets because ember-mapbox-composer still has the old models.

**Comment by allthesignals** [comment] 2018-10-10 20:11
@chriswhong thanks - I can work on that

**Comment by allthesignals** [comment] 2018-10-11 19:13
This is fixed in #v0.0.10

**Closed by allthesignals** 2018-10-11 19:13 UTC
Labels: in progress
